import type { FileDiff } from '../diff/parseDiff.js';

// CLAUDE.md non-negotiable 3: these are regenerated by their scripts and reviewed by the user, never edited to make
// a test pass. The web snapshot is left out: `npm run snapshot` refreshes it as routine data. The review check
// itself is protected too: a PR runs its own copy of the check, so an unseen edit to it could wave the PR through.
const PROTECTED_ROOTS = [
  'packages/fixtures/data/',
  'packages/fixtures/upstream/',
  'packages/fixtures/src/recorded/',
  'tools/review/',
  '.github/workflows/review.yml',
] as const;

/** Both paths count: a rename into a protected directory is as much a change as one out of it. */
export function protectedFiles(files: readonly FileDiff[]): string[] {
  const touched = files.flatMap((file) => [file.oldPath, file.newPath]);
  const hits = touched.filter((path): path is string => path !== null && isProtected(path));
  return [...new Set(hits)].sort();
}

function isProtected(path: string): boolean {
  return PROTECTED_ROOTS.some((root) => path.startsWith(root));
}
