import { z } from 'zod';
import { TOLERANCE_KINDS } from './groundTruth/loosening.js';
import { jevResponseSchema } from './typesafe/jevResponse.js';

// The labelled examples behind the recordings and the confidence cutoff. Labels were reviewed by the user before
// anything was recorded; the recordings themselves are regenerated by scripts/recordJev.ts, never edited.

const numberKindSchema = z.enum([...TOLERANCE_KINDS, 'not-a-tolerance']);

const numberChangeSchema = z.object({
  path: z.string(),
  newLineNumber: z.number().int(),
  oldLine: z.string(),
  newLine: z.string(),
  oldText: z.string(),
  newText: z.string(),
  oldValue: z.number(),
  newValue: z.number(),
  numberPosition: z.number().int().positive(),
  nearbyLines: z.array(z.string()),
});

export const toleranceExamplesSchema = z.array(
  z.object({ id: z.string(), expectedKind: numberKindSchema, change: numberChangeSchema }),
);

export const messageExamplesSchema = z.array(
  z.object({
    id: z.string(),
    kind: z.enum(['commit', 'pr']),
    text: z.string(),
    expected: z.object({ functionalOnly: z.boolean().optional(), plainEnglish: z.boolean() }),
  }),
);

export const recordingsSchema = z.array(
  z.object({ id: z.string(), request: z.unknown(), response: jevResponseSchema }),
);

export type ToleranceExample = z.infer<typeof toleranceExamplesSchema>[number];
export type MessageExample = z.infer<typeof messageExamplesSchema>[number];
export type Recording = z.infer<typeof recordingsSchema>[number];
